

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: kabeer@9930
      MYSQL_DATABASE: employeeTask
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  springboot:
    build: .
    container_name: task_springboot_project
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: employeeTask
      MYSQL_USER: root
      MYSQL_PASSWORD: kabeer@9930
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
